spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/photodb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    dirver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 60
      maxWait: 10000

mybatis:
  type-aliases-package: com.photo.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml